SHOW COLUMNS FROM hr.locations;

ALTER TABLE hr.locations CHANGE COLUMN STREET_ADDRESS ADDRESS VARCHAR(40);

SHOW COLUMNS FROM hr.regions;

ALTER TABLE hr.regions CHANGE COLUMN REGION_NAME REGION VARCHAR(25) UNIQUE; 

SHOW COLUMNS FROM hr.countries;

ALTER TABLE hr.countries CHANGE COLUMN COUNTRY_NAME COUNTRY VARCHAR(40);